// Generated by CoffeeScript 1.12.5
(function() {
  (function($) {
    window.getCookeParam = function(name) {
      var cookie, end, offset, result, search, setStr;
      cookie = " " + document.cookie;
      search = " " + name + "=";
      setStr = "";
      offset = 0;
      end = 0;
      if (cookie.length > 0) {
        offset = cookie.indexOf(search);
        if (offset !== -1) {
          offset += search.length;
          end = cookie.indexOf(";", offset);
          if (end === -1) {
            end = cookie.length;
          }
          setStr = decodeURI(cookie.substring(offset, end));
        }
      }
      return result = setStr;
    };
    window.getQueryParam = function(paramName) {
      var paramValue, params, pattern, queryString, tokens;
      queryString = document.location.search.split("+").join(" ");
      pattern = /[?&]?([^=]+)=([^&]*)/g;
      params = {};
      while (tokens = pattern.exec(queryString)) {
        params[decodeURIComponent(tokens[1])] = decodeURIComponent(tokens[2]);
      }
      return paramValue = params[paramName] === void 0 || params[paramName] === "" ? window.getCookeParam(paramName) : params[paramName];
    };
    window.setQueryParam = function(name, value, expires, path, domain, secure) {
      return document.cookie = name + "=" + encodeURI(value) + (expires ? "; expires=" + expires : "") + (path ? "; path=" + path : "") + (domain ? "; domain=" + domain : "") + (secure ? "; secure" : "");
    };
    window.getCPA_Label = function(labelName) {
      var labelValue, res;
      labelValue = window.getQueryParam(labelName);
      if (labelValue === "") {
        switch (labelName) {
          case "s":
            labelValue = document.location.hostname;
            break;
          case "w":
            labelValue = getQueryParam("utm_source");
            if (labelValue === "") {
              labelValue = "site";
            }
            break;
          case "p":
            labelValue = getQueryParam("utm_campaign");
            break;
          case "t":
            labelValue = getQueryParam("utm_content");
            break;
          case "m":
            labelValue = getQueryParam("utm_medium");
        }
      }
      if (labelName === "s" && /mtproxy\.yandex\.net$/.test(labelValue)) {
        console.log(labelValue);
        labelValue = document.location.hostname;
        console.log(labelValue);
      }
      return res = labelValue;
    };
    return window.getCPA_Location = function() {
      var res;
      return res = "s=" + window.getCPA_Label("s") + "&w=" + window.getCPA_Label("w") + "&p=" + window.getCPA_Label("p") + "&t=" + window.getCPA_Label("t") + "&m=" + window.getCPA_Label("m");
    };
  })(jQuery);

}).call(this);
